= Build an Neo4j-backed Chatbot using Python

This repository accompanies the link:https://graphacademy.neo4j.com/courses/llm-chatbot-python[Build an Neo4j-backed Chatbot using Python^] course on link:https://graphacademy.neo4j.com/?ref=github[Neo4j GraphAcademy^].

For a complete walkthrough of this repository, link:https://graphacademy.neo4j.com/courses/llm-chatbot-python/?ref=github[enrol now^].

link:https://codespaces.new/neo4j-graphacademy/llm-chatbot-python[image:https://github.com/codespaces/badge.svg[Open in GitHub Codespaces]^]

== Running the application

To run the application, you must install the libraries listed in `requirements.txt`.

[source,sh]
pip install -r requirements.txt


Then run the `streamlit run` command to start the app on link:http://localhost:8501/[http://localhost:8501/^].

[source,sh]
streamlit run bot.py

== Tests

To run the solution tests: 

. Create Neo4j instance with the `recommendations` dataset
. Run the link:https://raw.githubusercontent.com/neo4j-graphacademy/courses/refs/heads/main/asciidoc/courses/llm-chatbot-python/modules/3-tools/lessons/1-vector-tool/reset.cypher[Cypher to add embeddings and create the vector index^].
. Create a virtual environment and install the requirements.
+ 
[source,sh]
pip install -r requirements.txt
. Install `pytest`
+
[source,sh]
pip install pytest
. Create a `secrets.toml` file in the `.streamlit` directory. Use `secrets.toml.example` as a template.
. Run the tests
+
[source,sh]
pytest